name: sos_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.6
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  telephony: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
